using CruzNeryClinic.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System;
using System.Collections.Generic;
using System.IO;

namespace CruzNeryClinic.Services
{
    // Generates a printable PDF of the Help content. Each section
    // (User Manual / FAQs) is rendered only when items are supplied,
    // so the Help screen can print just the currently selected tab.
    // Mirrors ReceiptPDFService so the preview/print flows through
    // WebView2 the same way the Billing receipt does.
    public static class UserManualPDFService
    {
        public static string GenerateHelpPdf(
            IReadOnlyList<HelpManualTopic> topics,
            IReadOnlyList<FaqItem> faqs,
            string subtitle,
            string fileName)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            string manualsFolder = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "CruzNeryClinic",
                "Manuals"
            );

            Directory.CreateDirectory(manualsFolder);

            string filePath = Path.Combine(manualsFolder, fileName);

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(36);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily("Arial"));

                    page.Header().Element(header =>
                    {
                        header.Background("#223357").Padding(18).Column(col =>
                        {
                            col.Item().Text("CRUZ-NERY DENTAL CLINIC")
                                .FontSize(20)
                                .Bold()
                                .FontColor(Colors.White);

                            col.Item().PaddingTop(4).Text(subtitle)
                                .FontSize(12)
                                .FontColor(Colors.White);
                        });
                    });

                    page.Content().PaddingTop(24).Column(col =>
                    {
                        col.Spacing(14);

                        if (topics.Count > 0)
                        {
                            col.Item().Text("USER MANUAL")
                                .FontSize(16)
                                .Bold()
                                .FontColor("#223357");

                            foreach (HelpManualTopic topic in topics)
                            {
                                col.Item().PaddingTop(6).Text(topic.Title)
                                    .FontSize(13)
                                    .Bold()
                                    .FontColor("#111111");

                                col.Item().PaddingLeft(16).Text(topic.Content)
                                    .FontSize(10)
                                    .FontColor("#444444");
                            }
                        }

                        if (faqs.Count > 0)
                        {
                            col.Item().PaddingTop(topics.Count > 0 ? 18 : 0).Text("FREQUENTLY ASKED QUESTIONS")
                                .FontSize(16)
                                .Bold()
                                .FontColor("#223357");

                            foreach (FaqItem faq in faqs)
                            {
                                col.Item().PaddingTop(6).Text($"Q: {faq.Question}")
                                    .FontSize(12)
                                    .Bold()
                                    .FontColor("#111111");

                                col.Item().PaddingLeft(16).Text($"A: {faq.Answer}")
                                    .FontSize(10)
                                    .FontColor("#444444");
                            }
                        }
                    });

                    page.Footer().AlignCenter().Text(text =>
                    {
                        text.Span("This document was generated by Dental Clinic Management System.")
                            .FontSize(9)
                            .FontColor(Colors.Grey.Darken1);
                    });
                });
            }).GeneratePdf(filePath);

            return filePath;
        }
    }
}
